### ISSUE TITLE
Client leaking connections in the connection pool when target server crashes.

### ISSUE THREAD

**Issue by Gonzih** [ztellman/aleph#217]
Hi,

I just spotted an issue that workers are leaking in the connection pool if in the middle of request I remove target server (so connection is not closed properly). After that `num-workers` stat fluctuates between two values constantly (even when there are no requests coming to the server). So in stats logs i see something like that:

```
connections.localhost-9002 -> 620
connections.localhost-9002 -> 557
connections.localhost-9002 -> 620
connections.localhost-9002 -> 557
connections.localhost-9002 -> 620
connections.localhost-9002 -> 557
connections.localhost-9002 -> 620
connections.localhost-9002 -> 557
```

I tried to use all timeout options without any success.
I was able to reproduce that by just creating a lot of http/get requests to some simple web server that was just doing Thread/sleep and blocking them. Before timeout happens I just send kill -9 to the target server to simulate failure and after some time not all connections are released. I started digging in to that because I spotted that resources are slowly leaking from my server until there ane no available workers left. Is this related to this issue? Should I create a separate issue? Am I missing something here?

This is minimal code snippet that I was able to reproduce the issue with:

``` clojure
(defonce client-connection-pool
  (aleph/connection-pool
   {:response-executor
    (flow/utilization-executor
      0.9 512
      {:stats-callback (partial stats-callback :client)})
    :connections-per-host 7000
    :total-connections 8000
    :target-utilization 0.9
    :stats-callback connections-stats-callback ; dumps stats in to a file
    :connection-options {:keep-alive? false}}))

(->> 15000
     range
     (map (fn [_]
            (aleph/get "http://localhost:4567"
                       {:follow-redirects false
                        :throw-exceptions false
                        :pool client-connection-pool
                        :pool-timeout 1e4
                        :connection-timeout 1e4
                        :request-timeout 4e4})))
     doall
     (map (fn [_] nil)))
```

Server:

``` ruby
require 'sinatra'

get '/' do
  sleep 120
  "HI"
end
```

Killing ruby process (kill -9) in the middle of execution sometimes leaks workers in the connection pool.

**Comment by Gonzih** [comment]
I just noticed that netstat reports state of those leaked connections as CLOSE_WAIT.

**Comment by ztellman** [comment]
Hey, sorry I haven't gotten to this yet. My totally untested hypothesis
lines up with this, which is that the connections will close eventually,
but the TCP stack isn't quite done with them until they actually time out.
If you want to test this by running your test, waiting a few minutes, and
seeing if the connections are still in the pool, that would be helpful.

Otherwise, I can do it myself when I have the time. No big deal either way.

**Comment by Gonzih** [comment]
I'm not sure if that is the case. I waited for ~30 mins on my local 
tests and nothing changed. Also I have a server in production that leaks 
connections at a kind of fixed rate only to one target service (might be 
issues with the server, I was unable to investigate that). Is there a 
way to get insights on what is in the conneciton pool?

My research showed that this is happening in some other netty based 
clients. People suggest from time to time manually close what they call 
"idle connections". For now I solved it by recreating pool from time to 
time if they leaks too much automatically.

**Comment by ztellman** [comment]
Okay, my hypothesis was based on the fact that I'm just relying on Netty to tell me when the connection is closed, and I assumed Netty was handling that properly.  If not, maybe I'll have to figure out a workaround.  I'll look into it.

**Comment by Gonzih** [comment]
So my solution dose not exactly work as expected. I don't have issue with reaching connections per host limit, but I still see some connection with CLOSE_WAIT left after I shut down old workers pool. So yeah, I think some cleanup mechanism would be nice.

**Comment by Gonzih** [comment]
Seems like setting :raw-stream? true helps with the problem in my case. I wonder why. Is it possible that this is related to the response body processing?

**Comment by ztellman** [comment]
I'm pretty sure that `raw-stream?` shouldn't make any difference.  I'm also not able to reproduce this behavior on my laptop, which is running OS X.  Can you provide some more details about your environment?

**Comment by Gonzih** [comment]
raw-stream? did not really help, it just slowed rate at which 
connections are leaking. I'm running clojure app in docker (ubuunt 
14.04) on top of ubuntu 14.04 with openjdk 8.

My production leakage case is when I'm running clojure and jruby servers 
in one jvm (puma for ruby).
Clojure is user facing server that proxies some requests to jruby and 
some other services preserving original headers for request and response.
Only iin clojure <-> jruby case I notice connection leakage. I'm not 
sure why.

Do you have any tips on where should I look closer for more information?

Feels free to ask any questions about my setup or use case if that helps.

Thanks!

**Comment by ztellman** [comment]
Okay, I was trying to replicate your example by just running `ruby server.rb`, which uses WEBrick by default.  Frankly, I'm pretty confused as why this would differ at all with different languages, since the OS is responsible for cleaning up connections after a process disappears, but I'll try to do this in Ubuntu and see if I have more luck.

I don't know much about JRuby, so if you can give me an out-of-the-box reproducing example, that would help a lot.

**Comment by Gonzih** [comment]
So I think I might be on to something. But issue is here not with aleph, but with my jruby server that sometimes drops connections. Let me test my current fix on the jruby part for a couple of days and see if it's main cause of my problem.

Thanks a lot for your time on this one!

**Comment by shmish111** [comment]
I've come across this issue, I've had to stop using aleph for now and I am using clj-http. I could have used http-kit but I fear it may be an issue with the way Netty works and I'm not totally confident that http-kit wouldn't have a similar problem. Are you making any progress on this? Not sure what info I can give you to help except that I got it to fail on OSX as well.

My other question is what would the server be doing that could cause this on the client side? As I understand it the server must be closing the connections in a weird way and somehow aleph doesn't close them from the client side. I really don't understand this stuff but I want to know what is the server doing to cause this bug to show up? Could it be something to do with the fact that the server is running on kubernetes? There's quite a bit happening on the networking side of things there.

**Comment by ztellman** [comment]
@shmish111 was your server also running Ruby?

**Comment by shmish111** [comment]
No, http-kit

**Comment by Gonzih** [comment]
I implemented pool restart mechanism for now as a temporary solution and started working on moving most of ruby stuff in to clojure. So reducing load also reduced rate of leakage. Funny thing is that I also query one of internal http services with a much higher rate (magnitude of x5) and don't see any problem there (scala + play framework). So I'm assuming that something very spicify needs to happen on the target server side for issue to appear. I was suspecting content-length header, but after some investigation discarded this theory since ruby return correct value.

**Comment by stijnopheide** [comment]
We're seeing the same kind of behaviour in production. We have a pipeline of core.async processes that consumes data from different sources (web-servers running Apache/PHP, Drupal, Play 1.2 and ASP.Net). This system runs without any problems with the http-kit client making the requests, but once we swap it to aleph, after some time it will end up with too many open files being reported by the OS (Linux).

What would be a good way to monitor this behaviour to start looking for which requests are causing it?

**Comment by ztellman** [comment]
It's possible that the issue here is just  that the connection pool is trying to resize itself every 10 seconds, which often means closing connections.  If the OS is keeping the connections in CLOSE_WAIT, that might explain the "leakage", which is not necessarily permanent.

@stijnopheide, are you using the default connection pool, and what's your file descriptor limit for your process?  Can you try `0.4.2-alpha4`, which has a longer default `:control-period` for the pool?

**Comment by stijnopheide** [comment]
@ztellman I can reproduce it with the following settings for connection-pool:
```clojure
{:connections-per-host 20
 :total-connections    1024
 :target-utilization   0.9}
```
ulimits are
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31897
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 9000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31897
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
I will first try to reproduce this problem in a separate environment and then try with ```0.4.2-alpha4```.

**Comment by gsnewmark** [comment]
@ztellman I'm not 100% sure it's related to this issue, but Aleph client currently "throws" a [regular Clojure exception](https://github.com/ztellman/aleph/blob/5457870cdba22bc3f30891a3b95f3e484b9d8a42/src/aleph/http/client.clj#L345) when Netty [marks underlying channel as inactive](https://github.com/ztellman/aleph/blob/5457870cdba22bc3f30891a3b95f3e484b9d8a42/src/aleph/http/client.clj#L155), but then such [connections are returned back to the pool](https://github.com/ztellman/aleph/blob/5457870cdba22bc3f30891a3b95f3e484b9d8a42/src/aleph/http.clj#L239-L241) (as `clojure.lang.ExceptionInfo` is not a `TimeoutException`). Shouldn't those `connection was closed` connections be removed from the pool?

**Comment by ztellman** [comment]
The flow here is a bit tortuous, but the code, as-is, should not be causing issues.

* Whenever a connection is closed, it is automatically disposed: https://github.com/ztellman/aleph/blob/master/src/aleph/http.clj#L122
* When something is disposed from the Dirigiste pool, it removes a marker that denotes we still want to keep the object: https://github.com/ztellman/dirigiste/blob/master/src/io/aleph/dirigiste/Pool.java#L455
* Then, when the disposed object is released back to the pool, it's simply discarded: https://github.com/ztellman/dirigiste/blob/master/src/io/aleph/dirigiste/Pool.java#L443

I don't see any obvious bugs in this flow, but they could exist.  Let me know if you see something I'm overlooking.

**Comment by gsnewmark** [comment]
@ztellman at first glance I don't see any flows too, but at the same time we've definitely seen improvement with [this crude fix](https://github.com/OlegTheCat/aleph/commit/340c326994bbe96d5e2fe6de7539194993330b9b) - dangling `CLOSE_WAIT` connections disappeared completely. I don't have much time now, but I'll recheck the code first thing in the morning (it's evening right now in my timezone). The only thing that pops into my mind: could it be the case that connection is closed **before**  the close callback [is added to stream](https://github.com/ztellman/aleph/blob/5457870cdba22bc3f30891a3b95f3e484b9d8a42/src/aleph/http/client.clj#L329-L332)?

**Comment by ztellman** [comment]
When registering multiple callbacks, there's always possible race conditions.  I think being more explicit in our handling of errors makes sense regardless, especially if it empirically seems to help.  I'd like to understand this, though, to make sure it's not a sign of some issue in Dirigiste itself.

**Comment by OlegTheCat** [comment]
@ztellman, we use web-server (to be presice it's Erlang's Cowboy) that from time to time drops connections: roughly 5-10 dropped connections per hour with roughly 1k reqs/min load. 

It seems, that with fix that @gsnewmark mentioned leak still persists, but it has been slowed down. Without the fix there were 5-10 new dangling `CLOSE_WAIT` connections per hour (which correlates with Cowboy's connection drop rate), with the fix only 6 connections appeared to be in `CLOSE_WAIT` state over 15 hour period.

**Comment by gsnewmark** [comment]
@ztellman after some additional investigation I believe we've found the source of remaining 'leaked' connections. Under some weird circumstances [deferred with response's completion status](https://github.com/ztellman/aleph/blob/b70916db7067ba6fafa469dea7d43371d962d1dd/src/aleph/http.clj#L247) is never completed: as there is no explicit timeout Aleph connection is stuck in 'used' state (actual underlying connection transfers to the `CLOSE_WAIT` state), never returning to the pool, but prohibiting creation of the new connections (when max pool size is reached).

There're couple of places where response is marked as completed, but most of them are tied to the [close of the stream created from the underlying Netty channel](https://github.com/ztellman/aleph/blob/b70916db7067ba6fafa469dea7d43371d962d1dd/src/aleph/http/client.clj#L169). We can only reproduce this issue with Cowboy server that sometimes drops connections (@OlegTheCat already mentioned it) and I'm still not sure what causes response body stream to never close. 

For now we simply [added hard-coded timeout with explicit `dispose` to the `:aleph/complete` deferred handling](https://github.com/OlegTheCat/aleph/commit/6af62196c7b8535fea1712e9ff1588e30a7d8fcc) and now all connections are properly closed: our HTTP client is running for nearly a week without restarts and there is still no `CLOSE_WAIT` connections (previously we had a couple of them each day). Should we prepare a PR with configurable timeout or there is a better way to avoid the described problem?

**Comment by ztellman** [comment]
I think I'd like to make it an idle timeout rather than a hard time limit, because that would adversely affect people doing long poll requests or pulling down Twitter streams, etc.  If you want to open a pull request, great, otherwise I can add it in myself.

**Comment by moonpolysoft** [comment]
Just to chime in, I seem to be hitting this issue very consistently, specifically when getting an error condition from JIRA's REST API's (404, 500, etc).

**Comment by ztellman** [comment]
I wouldn't expect error responses to behave any differently, unless the connection lifecycle is handled differently by the server in those cases.  Since you seem to be able to easily reproduce this, though, can you add this and see if it changes anything?

```clj
(manifold.time/in 1e4 #(-> rsp .body manifold.stream/close!))
```

This will just make extra-sure that the stream is closed after 10 seconds (I'm assuming your response is called `rsp` here), which is hopefully enough time for JIRA to send its response.  If this fixes your issue, it confirms what @gsnewmark is reporting, and it will be a pretty straightforward fix.

**Comment by moonpolysoft** [comment]
Confirmed. The specific issue I was having was that, since this is an error condition I was trying to bs/to-string on the response bodies for logging, and it would gum up the thread pool pretty quickly since that function would never return. Putting that line of code in the d/catch block ensures that to-string is returning.

**Comment by ztellman** [comment]
To be clear, the `d/catch` clause is because the 4xx and 5xx responses are being returned as errors? I know this is the default behavior, but I just want to be sure.

**Comment by ztellman** [comment]
Hmm, I may have figured out the significance of the fact that error responses are causing this issue for you.  If I'm right, this should be fixed in `0.4.2-alpha10` without the change I described above.  Could you confirm?

**Comment by moonpolysoft** [comment]
Still shows the same behavior with 0.4.2-alpha10.

**Comment by maxcountryman** [comment]
So I'm running into what appears to be the same exception, also attempting to implement a proxy server. Nothing much to add here, only to say that I can also confirm `0.4.2-alpha10` still yields the issue.

**Comment by ztellman** [comment]
@maxcountryman does the workaround suggested earlier in the thread also fix the issue for you? I need to sit down and come up with a minimal reproducing case for this, but any additional data I can gather will help.

**Comment by moonpolysoft** [comment]
Since it's relatively easy for me to reproduce, you want me to pull
together a Wireshark of what happens?

**Comment by maxcountryman** [comment]
@ztellman I tried the snippet you mentioned above, `(manifold.time/in 1e4 #(-> rsp .body manifold.stream/close!))`, and it seemed to reduce the frequency of errors but did not stop them completely.

Happy to share the code I'm working with if it helps.

**Comment by ztellman** [comment]
@moonpolysoft yes, that would be a huge help

**Comment by ztellman** [comment]
@maxcountryman and yes, if you can share the code that would also help

**Comment by maxcountryman** [comment]
@ztellman I've tried to distill a simple test program. I will say that the particular server that's being proxied here is consistently throwing `clojure.lang.ExceptionInfo` whereas proxying other servers only yielded the error occasionally. Also I just started looking at Aleph yesterday so it's perfectly possible I'm doing something wrong here.

```cojure
(require '[aleph.http :as http])
(require '[manifold.deferred :as d])

(defn handler [req]
  (let [{:keys [request-method uri]} req]
    (->
      @(http/request {:method request-method
                      :url (str "https://www.rankscience.com" uri)
                      :raw-stream? true})
      (update-in [:headers] merge {"foo" "bar"}))))

(http/start-server handler {:port 8080 :raw-stream? true})
```

**Comment by maxcountryman** [comment]
Following up with my last message: the particular error with rankscience.com is related to an SSL handshake failure (worth noting that clj-http does not seem to have this issue, however).

A better example might be `"https://coderwall.com"`.  Triggering the error with coderwall.com takes a bit more work, but I was able to see it with fair consistency by navigating around site and refreshing pages a few times.

For example, after refreshing a couple of times, I see: `clojure.lang.ExceptionInfo: connection was closed`.

**Comment by ztellman** [comment]
I'll play around with it and see what I can find, thanks.

**Comment by ztellman** [comment]
@maxcountryman the issue you were having with the `https://rankscience.com` request seems to have been resolved by targeting the latest Netty.  Likewise, I can't reproduce any such issue with coderwall, either.

It's possible this a different issue than the one reported in this thread, but I would expect it to be resolved in `0.4.2-alpha12`.

**Comment by maxcountryman** [comment]
@ztellman updating to `0.4.2-alpha12` does seem to resolve the SSL handshake error, however I'm still seeing the same exception, `clojure.lang.ExceptionInfo: connection was closed`, when refreshing certain Coderwall pages, e.g. `/t/ruby/popular` seems to produce the error every ten refreshes or so.

**Comment by ztellman** [comment]
Hmm, I'm not able to reproduce that.  Can you provide more information about your JVM, OS, etc?

**Comment by maxcountryman** [comment]
@ztellman Java 1.8.0_111 on macOS 10.12.2 Beta (16C32f). I'm not using any custom JVM options in my `project.clj`. I'm running the project via `lein run` and am using `:gen-class` in my `ns` definition.

```
$ lein deps :tree
Possibly confusing dependencies found:
[cider/cider-nrepl "0.8.1"] -> [org.clojure/tools.namespace "0.2.5" :exclusions [org.clojure/clojure]]
 overrides
[com.jakemccrary/lein-test-refresh "0.15.0"] -> [org.clojure/tools.namespace "0.2.11" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[com.jakemccrary/lein-test-refresh "0.15.0" :exclusions [org.clojure/tools.namespace]]

 [aleph "0.4.2-alpha12"]
   [byte-streams "0.2.2"]
     [clj-tuple "0.2.2"]
     [primitive-math "0.1.5"]
   [manifold "0.1.6-alpha4"]
     [io.aleph/dirigiste "0.1.5-alpha1"]
     [riddley "0.1.12"]
   [org.clojure/tools.logging "0.3.1" :exclusions [[org.clojure/clojure]]]
   [potemkin "0.4.3"]
 [cider/cider-nrepl "0.8.1"]
   [cljs-tooling "0.1.3" :exclusions [[org.clojure/clojure]]]
   [compliment "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/java.classpath "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.namespace "0.2.5" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.trace "0.7.8" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [cljfmt "0.3.0"]
   [rewrite-clj "0.4.12"]
     [org.clojure/tools.reader "0.8.13" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [io.netty/netty-all "4.1.6.Final"]
 [org.clojure/clojure "1.9.0-alpha14"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [rhizome "0.2.5"]
```

**Comment by maxcountryman** [comment]
@ztellman thanks for looking at this with me today: as we discovered, my issue is not related to the connection pool and in fact my JVM was out of date. Updating the Java development environment to the latest release fixed the issues I reported. Thanks!

**Comment by ztellman** [comment]
@moonpolysoft do you think you can provide a packet dump at some point in the near future?  I'm trying to get a release out the door, and would like to address this beforehand if at all possible.

**Comment by moonpolysoft** [comment]
Oh yeah it had slipped my mind. Will put one together shortly

**Comment by moonpolysoft** [comment]
Curiously, I am no longer able to reproduce after walking back the timeout bandaid. Maybe they fixed the error handling in JIRA cloud somehow?

**Comment by ztellman** [comment]
Hmmm, there was a legit connection leak in earlier versions where the response was a 4xx or 5xx, `:throw-exceptions?` was true (which it is by default), and the server didn't close the connection on error responses.  After addressing that, I was pretty surprised that you were still seeing the same behavior.

It's very possible that JIRA did something on their end (it takes both sides to create a leak), but I've been banging my head against this long enough, and have a plausible enough explanation for everyone's issues but yours, so I'm tempted to just close the issue and see what the future holds.  Any objections?

**Comment by stoyle** [comment]
First, thanks for Aleph, we think it is just great.

This is a pretty long thread, and haven't gone though the entire thing. But aleph 0.4.1 had issues on ubuntu. Worked fine on Mac, but on the server a lot of the client request took a really long time. It seems they eventually completed, but this was long after the browser client cut the connection, e.g. 2-3 minutes later.

Bumping to 0.4.2-alpha12, and it behaves perfectly on the server... Now we load about 84 requests concurrently in the expected time, 2-3 seconds

So at least for me, this is a +1 for release.

Cheers,
Alf

**Comment by ztellman** [comment]
Thank you, that's a really helpful data point.
